# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: R-CMD-CHECK

on:
  push:
  pull_request:

env:
  USE_BSPM: "true"
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: macOS-latest,   r: release}
          - {os: windows-latest, r: release}
          - {os: windows-latest, r: 3.6}
          - {os: ubuntu-latest,  r: devel}
          - {os: ubuntu-latest,  r: release}
          - {os: ubuntu-latest,  r: 3.6}


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: eddelbuettel/github-actions/r-ci@master

      - name: Dependencies
        run: ./run.sh install_all

      - name: Test
        run: ./run.sh run_tests
      # - name: Coverage
      #   run: ./run.sh coverage
